### ISSUE TITLE
Output unit of measurement

### ISSUE THREAD

**Issue by tommy15979** [erellaz/seisberry#1]
Hi,
I just completed your awesome project.
Now i can register all data on TXT, but i don't understand if the file contains the Voltage of geophone or, in some way, you convert this voltage to mm/s or m/s.
In this case, i don't know how to modify main.c to consider geophone sensitivity (V/cm/s).

**Comment by erellaz** [comment]
Glad you made one!
To your question:
- the geophone manufacturer will provide you with a spec sheet showing the sensitivity in v/m/s. For example on the sheet linked below I read 20V per m/s in the frequency range where the sensitivity remains a constant (that is from 10hz to Nyquist frequency).
https://rtclark.com/wp-content/uploads/2015/10/RTC-10hz-395-Spec-Curve-Email.pdf
- the C program has 2 gains: one hardware gain passed to the board, and one software gain, used to multiply the value delivered by the board before writing to the text file. 

Therefore the products of the software gain by the hardware gain by the geophone manufacturer sensitivity gives you the scale factor between the value written out by the program in the text file and the velocity measured by the geophone.

Here is how to QC and calibrate this. Replace the geophone by a known calibrated constant voltage of a few millivolts (or the signal generator of an oscilloscope), and make sure what you record in the text file has exactly the value of the input voltage as delivered by your calibrated source. If it does, introduce the geophone sensitivity in the scale factor and put the geophone back.

I will leave this ticket open until I have rigorously verified the gain application in the C program and on the board -or if you confirm the problem is solved on your side.

**Comment by tommy15979** [comment]
Ok.
For example, my Geophone specs are (LGT-20D10):
http://www.longetequ.com/geophone/5.htm
So, making the product = 1, I can modify parameters file using:
Ampgain=64
Numgain=0.078125
In this case 64x0,2x0.078125 = 1

then I can try to calibrate it with oscilloscope!

**Comment by erellaz** [comment]
Yes, I think so. I have not tested it yet though. 

I realize what I need is allow the user to enter the geophone sensitivity (straight from sensor manufacturer specs) in the param file, and optionally the pre-amplifier gain (for those who want to fine tune dynamic and over-scaling). Then the program should automatically calculate the electronic gain so the result is always calibrated in m/s.

I will do that and test it with the various geophones I have, but that make take a little time.

**Comment by tommy15979** [comment]
Unfortunately i am able only to develop windows software (vb/c#). I think that a userform would be useful. For example, to start/stop logging and to set param file

**Comment by tommy15979** [comment]
Hi, have you tried to modify config file? If you want i can do some test

**Comment by erellaz** [comment]
BTW, I also added a GUI:
https://github.com/erellaz/seisberry/blob/master/SeismographGUI.py

**Comment by erellaz** [comment]
Here is a step by step tutorial to do the calibration and test the instrument with an oscilloscope.
This was fully tested on 8/30/2020, and it works.
https://erellaz.com/blog/seisberry/calibrating-a-seisberry/
